### ISSUE TITLE
MicrosoftWindowsDesktop:Windows-10:19h1-pron:latest' is not available.

### ISSUE THREAD

**Issue by rstar13as** [christophetd/Adaz#58] opened 2023-12-21 06:01 UTC
**What is not working?**

After running terraform apply; get the following error.

╷
│ Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="PlatformImageNotFound" Message="The platform image 'MicrosoftWindowsDesktop:Windows-10:19h1-pron:latest' is not available. Verify that all fields in the storage profile are correct. For more details about storage profile information, please refer to https://aka.ms/storageprofile" Target="imageReference"
│ 
│   with azurerm_virtual_machine.workstation[1],
│   on workstations.tf line 23, in resource "azurerm_virtual_machine" "workstation":
│   23: resource "azurerm_virtual_machine" "workstation" {
│ 
╵
╷
│ Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="PlatformImageNotFound" Message="The platform image 'MicrosoftWindowsDesktop:Windows-10:19h1-pron:latest' is not available. Verify that all fields in the storage profile are correct. For more details about storage profile information, please refer to https://aka.ms/storageprofile" Target="imageReference"
│ 
│   with azurerm_virtual_machine.workstation[0],
│   on workstations.tf line 23, in resource "azurerm_virtual_machine" "workstation":
│   23: resource "azurerm_virtual_machine" "workstation" {
│ 
╵

**What OS are you using?**
 Mac OS X

**Your `domain.yml` file?**
If you customized the `domain.yml` file, please include it below

No, customisation 

**Full Terraform / Ansible output?**
If applicable, please include the full Terraform / Ansible output

**Comment by christophetd** [comment] 2023-12-21 09:50
Thanks for reporting! Having a look now.

**Comment by christophetd** [comment] 2023-12-21 10:05
Reproduced

**Comment by christophetd** [comment] 2023-12-21 11:39
should be fixed by https://github.com/christophetd/Adaz/pull/59, can you checkout this branch and confirms it solves the issue? (works for me at least)

```
git fetch origin
git checkout win10-version-fix
cd terraform
terraform apply
```

**Comment by rstar13as** [comment] 2023-12-21 23:18
I completed the above commands, and get a new error, which i cant tell is related to the above change or preexisting; Not sure why it would for you and not me either, doesnt make sense, but then again. terraform is flaky 

ull_resource.provision_workstation_once_dc_has_been_created: Creation complete after 4m29s [id=3718332494816085520]
╷
│ Error: waiting for completion of Security Group Association for Network Interface: (Name "ad-lab-wks-0-nic" / Resource Group "ad-hunting-lab"): Code="InternalServerError" Message="An error occurred." Details=[]
│ 
│   with azurerm_network_interface_security_group_association.workstation[0],
│   on workstations.tf line 17, in resource "azurerm_network_interface_security_group_association" "workstation":
│   17: resource "azurerm_network_interface_security_group_association" "workstation" {
│ 
╵

**Comment by rstar13as** [comment] 2023-12-21 23:26
destroy also failed,

╷
│ Error: deleting Network Security Group "windows-nsg" (Resource Group "ad-hunting-lab"): network.SecurityGroupsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseNetworkSecurityGroupCannotBeDeleted" Message="Network security group /subscriptions/7c6680e5-9965-4c61-8116-e54631e18e57/resourceGroups/ad-hunting-lab/providers/Microsoft.Network/networkSecurityGroups/windows-nsg cannot be deleted because it is in use by the following resources: /subscriptions/7c6680e5-9965-4c61-8116-e54631e18e57/resourceGroups/ad-hunting-lab/providers/Microsoft.Network/networkInterfaces/ad-lab-wks-0-nic. In order to delete the Network security group, remove the association with the resource(s). To learn how to do this, see aka.ms/deletensg." Details=[]
│ 
│

**Comment by rstar13as** [comment] 2023-12-21 23:42
The destroy command didn't delete a few resources, so I manually deleted them and testing again.

**Comment by rstar13as** [comment] 2023-12-22 05:14
Thank you very much, ran the above commands and the build was successful,  please can you advise the cause and your fix for this issues and changes made?

**Closed** 2023-12-22 09:16 UTC
Labels: bug

**Comment by christophetd** [comment] 2023-12-22 09:17
See changes here: https://github.com/christophetd/Adaz/pull/59/files

- I updated the image to `win10-22h2-pron` (the Windows 10 19h1 version wasn't available anymore)
- Since this is a gen2 image, I had to bump the instance type to `Standard_DS1_v2`
- For some reason, also had to explicitly force NTLM WinRM authentication on Ansible

Glad it's solved! Now merged into the main branch. Thanks again for reporting
